springdoc:
    api-docs:
        path: /auth/api-docs
    swagger-ui:
        operationsSorter: method
        path: /auth/swagger-ui-custom.html

auth:
    cors:
        allowedOrigins: http://localhost:3000
    token:
        expirationInMils: '#{1000 * 60 * 60 * 24}'
        jwtSecret: ${JWT_SECRET}

server:
    port: 8080
spring:
    datasource:
        password: ${DATABASE_PASSWORD}
        url: jdbc:postgresql://localhost:5432/${DATABASE_NAME}?autoreconnect=true&createDatabaseIfNotExist=true&characterEncoding=utf8
        username: ${DATABASE_USER}
    jpa:
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        show-sql: true
    servlet:
        multipart:
            enabled: true
            max-file-size: 4MB
            max-request-size: 4MB